function [dgMotion, daMotion] = allcondition_cols()
% ALLCONDITION_COLS  The 8 motion-condition column names per experiment.
%
% Together with cfg.<exp>.oriCols (4 stationary) and cfg.<exp>.blank these are the 13
% conditions GLMsingle estimated, and the 13 over which each vertex's beta_mean /
% beta_std were computed. The motion conditions are not analysed in Figs 5-8, which
% makes them useful as an effect-independent normaliser.

    dgMotion = { ...
        'cartexp_vertical_grating_rightwards_motion', ...
        'cartexp_horizontal_grating_upwards_motion', ...
        'cartexp_vertical_grating_leftwards_motion', ...
        'cartexp_horizontal_grating_downwards_motion', ...
        'cartexp_leftleaning_grating_upperrightwards_motion', ...
        'cartexp_rightleaning_grating_upperleftwards_motion', ...
        'cartexp_leftleaning_grating_lowerleftwards_motion', ...
        'cartexp_rightleaning_grating_lowerrightwards_motion'};

    daMotion = { ...
        'polexp_pinwheel_grating_clockwise_motion', ...
        'polexp_annulus_grating_outwards_motion', ...
        'polexp_pinwheel_grating_cclockwise_motion', ...
        'polexp_annulus_grating_inwards_motion', ...
        'polexp_ccspiral_grating_clockoutwards_motion', ...
        'polexp_cspiral_grating_cclockoutwards_motion', ...
        'polexp_ccspiral_grating_cclockinwards_motion', ...
        'polexp_cspiral_grating_clockinwards_motion'};
end
