function [stimNames, stimMap] = createStimMap()

    stimNames = {'cartexp_vertical_grating_rightwards_motion', 'cartexp_horizontal_grating_upwards_motion', ...
    'cartexp_vertical_grating_leftwards_motion', 'cartexp_horizontal_grating_downwards_motion', ...
    'cartexp_leftleaning_grating_upperrightwards_motion', 'cartexp_rightleaning_grating_upperleftwards_motion', ...
    'cartexp_leftleaning_grating_lowerleftwards_motion', 'cartexp_rightleaning_grating_lowerrightwards_motion', ...
    'cartexp_horizontal_stationary', 'cartexp_vertical_stationary', 'cartexp_rightleaning_grating_stationary', ...
    'cartexp_leftleaning_grating_stationary', 'cartexp_blank', ...
    'polexp_pinwheel_grating_clockwise_motion', 'polexp_annulus_grating_outwards_motion', ...
    'polexp_pinwheel_grating_cclockwise_motion', 'polexp_annulus_grating_inwards_motion', ...
    'polexp_ccspiral_grating_clockoutwards_motion', 'polexp_cspiral_grating_cclockoutwards_motion', ...
    'polexp_ccspiral_grating_cclockinwards_motion', 'polexp_cspiral_grating_clockinwards_motion', ...
    'polexp_annulus_grating_stationary', 'polexp_pinwheel_grating_stationary', 'polexp_cspiral_grating_stationary', ...
    'polexp_ccspiral_grating_stationary', 'polexp_blank'};


    stimMap = struct();

    %% Cartesian moving stimuli
    stimMap.cartexp_vertical_grating_rightwards_motion = ...
        struct('type','cart','ori',90,'motdir',0);
    
    stimMap.cartexp_horizontal_grating_upwards_motion = ...
        struct('type','cart','ori',0,'motdir',90);
    
    stimMap.cartexp_vertical_grating_leftwards_motion = ...
        struct('type','cart','ori',90,'motdir',180);
    
    stimMap.cartexp_horizontal_grating_downwards_motion = ...
        struct('type','cart','ori',0,'motdir',270);
    
    stimMap.cartexp_leftleaning_grating_upperrightwards_motion = ...
        struct('type','cart','ori',135,'motdir',45);
    
    stimMap.cartexp_rightleaning_grating_upperleftwards_motion = ...
        struct('type','cart','ori',45,'motdir',135);
    
    stimMap.cartexp_leftleaning_grating_lowerleftwards_motion = ...
        struct('type','cart','ori',135,'motdir',225);
    
    stimMap.cartexp_rightleaning_grating_lowerrightwards_motion = ...
        struct('type','cart','ori',45,'motdir',315);
    
    
    %% Cartesian stationary
    stimMap.cartexp_horizontal_stationary = ...
        struct('type','cart','ori',0,'motdir',[]);
    
    stimMap.cartexp_vertical_stationary = ...
        struct('type','cart','ori',90,'motdir',[]);
    
    stimMap.cartexp_rightleaning_grating_stationary = ...
        struct('type','cart','ori',45,'motdir',[]);
    
    stimMap.cartexp_leftleaning_grating_stationary = ...
        struct('type','cart','ori',135,'motdir',[]);
    
    
    %% Blank
    stimMap.cartexp_blank = ...
        struct('type','cart','blank',true);


    %% Polar moving stimuli
    
    stimMap.polexp_pinwheel_grating_clockwise_motion = ...
        struct('type','pol','oriOffset',0,'motOffset',270);
    
    stimMap.polexp_annulus_grating_outwards_motion = ...
        struct('type','pol','oriOffset',90,'motOffset',0);
    
    stimMap.polexp_pinwheel_grating_cclockwise_motion = ...
        struct('type','pol','oriOffset',0,'motOffset',90);
    
    stimMap.polexp_annulus_grating_inwards_motion = ...
        struct('type','pol','oriOffset',90,'motOffset',180);
    
    stimMap.polexp_ccspiral_grating_clockoutwards_motion = ...
        struct('type','pol','oriOffset',45,'motOffset',315);
    
    stimMap.polexp_cspiral_grating_cclockoutwards_motion = ...
        struct('type','pol','oriOffset',135,'motOffset',45);
    
    stimMap.polexp_ccspiral_grating_cclockinwards_motion = ...
        struct('type','pol','oriOffset',45,'motOffset',135);
    
    stimMap.polexp_cspiral_grating_clockinwards_motion = ...
        struct('type','pol','oriOffset',135,'motOffset',225);
    
    
    %% Polar stationary
    
    stimMap.polexp_annulus_grating_stationary = ...
        struct('type','pol','oriOffset',90,'motdir',[]);
    
    stimMap.polexp_pinwheel_grating_stationary = ...
        struct('type','pol','oriOffset',0,'motdir',[]);
    
    stimMap.polexp_cspiral_grating_stationary = ...
        struct('type','pol','oriOffset',135,'motdir',[]);
    
    stimMap.polexp_ccspiral_grating_stationary = ...
        struct('type','pol','oriOffset',45,'motdir',[]);
    
    
    %% Polar blank
    
    stimMap.polexp_blank = ...
        struct('type','pol','blank',true);

end